RapChieuPhim/src/java/model/DatVe.java
package model;

public class DatVe {
    /*
    	ID int identity(1,1) primary key,
	LichChieuId int references LichChieu(ID),
	NguoiDungId int not null,
	LoaiNDId int not null,
	Ngay nvarchar(15) not null,
	TongTien int not null,
	foreign key (NguoiDungId, LoaiNDId) references NguoiDung(ID, LoaiId)
    */
    private int ID;
    private LichChieu lichChieu;
    private NguoiDung nguoiDung;
    private String Ngay;
    private int TongTien;

    public DatVe() {
    }

    public DatVe(int ID, LichChieu lichChieu, NguoiDung nguoiDung, String Ngay, int TongTien) {
        this.ID = ID;
        this.lichChieu = lichChieu;
        this.nguoiDung = nguoiDung;
        this.Ngay = Ngay;
        this.TongTien = TongTien;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public LichChieu getLichChieu() {
        return lichChieu;
    }

    public void setLichChieu(LichChieu lichChieu) {
        this.lichChieu = lichChieu;
    }

    public NguoiDung getNguoiDung() {
        return nguoiDung;
    }

    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

    public String getNgay() {
        return Ngay;
    }

    public void setNgay(String Ngay) {
        this.Ngay = Ngay;
    }

    public int getTongTien() {
        return TongTien;
    }

    public void setTongTien(int TongTien) {
        this.TongTien = TongTien;
    }
    
}

RapChieuPhim/src/java/model/Ghe.java
package model;

public class Ghe {
    /*
    ID int not null,
	HangGhe char(2) not null,
	STT int not null,
	PhongId int references PhongChieu(ID),
	LoaiGheId int references LoaiGhe(ID),
	primary key (ID, PhongId)
    */
    
    private int ID;
    private String HangGhe ;
    private int STT;
    private int PhongId;
    private LoaiGhe loaiGhe;

    public Ghe() {
    }

    public Ghe(int ID, String HangGhe, int STT, int PhongId, LoaiGhe loaiGhe) {
        this.ID = ID;
        this.HangGhe = HangGhe;
        this.STT = STT;
        this.PhongId = PhongId;
        this.loaiGhe = loaiGhe;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getHangGhe() {
        return HangGhe;
    }

    public void setHangGhe(String HangGhe) {
        this.HangGhe = HangGhe;
    }

    public int getSTT() {
        return STT;
    }

    public void setSTT(int STT) {
        this.STT = STT;
    }

    public int getPhongId() {
        return PhongId;
    }

    public void setPhongId(int PhongId) {
        this.PhongId = PhongId;
    }

    public LoaiGhe getLoaiGhe() {
        return loaiGhe;
    }

    public void setLoaiGhe(LoaiGhe loaiGhe) {
        this.loaiGhe = loaiGhe;
    }
    
    
}

RapChieuPhim/src/java/model/LichChieu.java
package model;

import java.sql.Date;
import java.sql.Time;

public class LichChieu {
    /*
    ID int identity(1,1) primary key,
	PhimId int references Phim(ID),
	PhongId int references PhongChieu(ID),
	NgayId int references NgayChieu(ID),
	BatDau time not null,
	KetThuc time not null,
    */
    
    private int ID, PhimId, PhongId, NgayId;
    private Time BatDau , KetThuc ;

    public LichChieu() {
    }

    public LichChieu(int ID, int PhimId, int PhongId, int NgayId, Time BatDau, Time KetThuc) {
        this.ID = ID;
        this.PhimId = PhimId;
        this.PhongId = PhongId;
        this.NgayId = NgayId;
        this.BatDau = BatDau;
        this.KetThuc = KetThuc;
    }
    
    

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public int getPhimId() {
        return PhimId;
    }

    public void setPhimId(int PhimId) {
        this.PhimId = PhimId;
    }

    public int getPhongId() {
        return PhongId;
    }

    public void setPhongId(int PhongId) {
        this.PhongId = PhongId;
    }

    public int getNgayId() {
        return NgayId;
    }

    public void setNgayId(int NgayId) {
        this.NgayId = NgayId;
    }

    public Time getBatDau() {
        return BatDau;
    }

    public void setBatDau(Time BatDau) {
        this.BatDau = BatDau;
    }

    public Time getKetThuc() {
        return KetThuc;
    }

    public void setKetThuc(Time KetThuc) {
        this.KetThuc = KetThuc;
    }

    
    
}

RapChieuPhim/src/java/model/LoaiND.java
package model;

public class LoaiND {
    /*
    	ID int primary key,
	TenLoai nvarchar(50) not null,
    */
    private int ID;
    private String TenLoai ;

    public LoaiND() {
    }

    public LoaiND(int ID, String TenLoai) {
        this.ID = ID;
        this.TenLoai = TenLoai;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getTenLoai() {
        return TenLoai;
    }

    public void setTenLoai(String TenLoai) {
        this.TenLoai = TenLoai;
    }
    
}

RapChieuPhim/src/java/model/NgayChieu.java
package model;

import java.sql.Date;

public class NgayChieu {
    private int ID;
    private Date NgayChieu ;

    public NgayChieu() {
    }

    public NgayChieu(int ID, Date NgayChieu) {
        this.ID = ID;
        this.NgayChieu = NgayChieu;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public Date getNgayChieu() {
        return NgayChieu;
    }

    public void setNgayChieu(Date NgayChieu) {
        this.NgayChieu = NgayChieu;
    }
    
}

RapChieuPhim/src/java/model/NguoiDung.java
package model;

public class NguoiDung {
    /*
        ID int not null,
	HoTen nvarchar(50) not null,
	Sdt char(10) not null,
	Email nvarchar(50) not null, 
	MatKhau nvarchar(50) not null,
	LoaiId int references LoaiND(ID),
    */
    private int ID;
    private String HoTen , Sdt, Email, MatKhau;
    private LoaiND loaiND;

    public NguoiDung() {
    }

    public NguoiDung(int ID, String HoTen, String Sdt, String Email, String MatKhau, LoaiND loaiND) {
        this.ID = ID;
        this.HoTen = HoTen;
        this.Sdt = Sdt;
        this.Email = Email;
        this.MatKhau = MatKhau;
        this.loaiND = loaiND;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getHoTen() {
        return HoTen;
    }

    public void setHoTen(String HoTen) {
        this.HoTen = HoTen;
    }

    public String getSdt() {
        return Sdt;
    }

    public void setSdt(String Sdt) {
        this.Sdt = Sdt;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getMatKhau() {
        return MatKhau;
    }

    public void setMatKhau(String MatKhau) {
        this.MatKhau = MatKhau;
    }

    public LoaiND getLoaiND() {
        return loaiND;
    }

    public void setLoaiND(LoaiND loaiND) {
        this.loaiND = loaiND;
    }

    
}

RapChieuPhim/src/java/model/Phim.java
package model;

import java.sql.Date;

public class Phim { 
    private int ID;
    private String TenPhim, DichTenPhim, HinhAnh, TheLoai, Nsx, DaoDien, DienVien, QuocGia;
    private Date NgayKhoiChieu;
    private String Trailer, NDPhim;

    public Phim() {
    }

    public Phim(int ID, String TenPhim, String DichTenPhim, String HinhAnh, String TheLoai, String Nsx, String DaoDien, String DienVien, String QuocGia, Date NgayKhoiChieu, String Trailer, String NDPhim) {
        this.ID = ID;
        this.TenPhim = TenPhim;
        this.DichTenPhim = DichTenPhim;
        this.HinhAnh = HinhAnh;
        this.TheLoai = TheLoai;
        this.Nsx = Nsx;
        this.DaoDien = DaoDien;
        this.DienVien = DienVien;
        this.QuocGia = QuocGia;
        this.NgayKhoiChieu = NgayKhoiChieu;
        this.Trailer = Trailer;
        this.NDPhim = NDPhim;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getTenPhim() {
        return TenPhim;
    }

    public void setTenPhim(String TenPhim) {
        this.TenPhim = TenPhim;
    }

    public String getDichTenPhim() {
        return DichTenPhim;
    }

    public void setDichTenPhim(String DichTenPhim) {
        this.DichTenPhim = DichTenPhim;
    }

    public String getHinhAnh() {
        return HinhAnh;
    }

    public void setHinhAnh(String HinhAnh) {
        this.HinhAnh = HinhAnh;
    }

    public String getTheLoai() {
        return TheLoai;
    }

    public void setTheLoai(String TheLoai) {
        this.TheLoai = TheLoai;
    }

    public String getNsx() {
        return Nsx;
    }

    public void setNsx(String Nsx) {
        this.Nsx = Nsx;
    }

    public String getDaoDien() {
        return DaoDien;
    }

    public void setDaoDien(String DaoDien) {
        this.DaoDien = DaoDien;
    }

    public String getDienVien() {
        return DienVien;
    }

    public void setDienVien(String DienVien) {
        this.DienVien = DienVien;
    }

    public String getQuocGia() {
        return QuocGia;
    }

    public void setQuocGia(String QuocGia) {
        this.QuocGia = QuocGia;
    }

    public Date getNgayKhoiChieu() {
        return NgayKhoiChieu;
    }

    public void setNgayKhoiChieu(Date NgayKhoiChieu) {
        this.NgayKhoiChieu = NgayKhoiChieu;
    }

    public String getTrailer() {
        return Trailer;
    }

    public void setTrailer(String Trailer) {
        this.Trailer = Trailer;
    }

    public String getNDPhim() {
        return NDPhim;
    }

    public void setNDPhim(String NDPhim) {
        this.NDPhim = NDPhim;
    }

    
}

RapChieuPhim/src/java/model/RapChieu.java
package model;

public class RapChieu {
    /*
    	ID int not null,
	TenRap nvarchar(50) not null,
	DiaChi nvarchar(255) not null,
    */
    private int ID;
    private String TenRap , DiaChi, HinhAnh ;

    public RapChieu() {
    }

    public RapChieu(int ID, String TenRap, String DiaChi, String HinhAnh) {
        this.ID = ID;
        this.TenRap = TenRap;
        this.DiaChi = DiaChi;
        this.HinhAnh = HinhAnh;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getTenRap() {
        return TenRap;
    }

    public void setTenRap(String TenRap) {
        this.TenRap = TenRap;
    }

    public String getDiaChi() {
        return DiaChi;
    }

    public void setDiaChi(String DiaChi) {
        this.DiaChi = DiaChi;
    }

    public String getHinhAnh() {
        return HinhAnh;
    }

    public void setHinhAnh(String HinhAnh) {
        this.HinhAnh = HinhAnh;
    }

    
}

RapChieuPhim/src/java/controller/CTPhimDatveServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package controller;

import dal.LichChieuDAO;
import dal.NgayChieuDAO;
import dal.PhimDAO;
import dal.RapChieuDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import model.LichChieu;
import model.NgayChieu;
import model.Phim;
import model.RapChieu;

/**
 *
 * @author Admin
 */
public class CTPhimDatveServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        String PhimId_raw = request.getParameter("ID");
        int PhimId;
        try {
            PhimId = Integer.parseInt(PhimId_raw);
            RapChieuDAO dao = new RapChieuDAO();
            List<RapChieu> list = dao.getAllRapChieu();
            request.setAttribute("rap", list);
            request.setAttribute("phimId", PhimId);
            request.getRequestDispatcher("ctphim_datve.jsp").forward(request, response);
        } catch(NumberFormatException e){
            System.out.println(e);
        }
    } 

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        PhimDAO dao = new PhimDAO();
        List<Phim> phim = dao.getAllPhim(); 
        RapChieuDAO dao2 = new RapChieuDAO();
        List<RapChieu> rap = dao2.getAllRapChieu();
        request.setAttribute("phim", phim);
        request.setAttribute("rap", rap);
        
        String PhimId_raw = request.getParameter("phim");
        String RapId_raw = request.getParameter("rap");
        int PhimId, RapId;
        try {
            if(PhimId_raw!=null && RapId_raw!=null){
                PhimId = Integer.parseInt(PhimId_raw);
                request.setAttribute("phimId", PhimId);
                RapId = Integer.parseInt(RapId_raw);
                Phim p = dao.getPhimByID(PhimId);
                RapChieu r = dao2.getRapChieuByID(RapId);
                request.setAttribute("p", p.getTenPhim());
                System.out.println(p.getTenPhim());
                request.setAttribute("r", r.getTenRap());
                System.out.println(r.getTenRap());
                LichChieuDAO dao3 = new LichChieuDAO();
                List<LichChieu> lich = dao3.getAllLichChieuByPhimIdAndRapId(PhimId, RapId);
                request.setAttribute("lich", lich);
                for(LichChieu i:lich){
                    System.out.println(i.getBatDau());
                }
                NgayChieuDAO dao4 = new NgayChieuDAO();
                List<NgayChieu> ngay = dao4.getAllNgayChieuByPhimIdAndRapId(PhimId, RapId);
                request.setAttribute("ngay", ngay);
                for(NgayChieu i:ngay){
                    System.out.println(i.getNgayChieu());
                }
            }
            else {
                request.setAttribute("phimId", PhimId_raw);
            }
            
            
        } catch (NumberFormatException e) {
            System.out.println(e);
        }
        request.getRequestDispatcher("ctphim_datve.jsp").forward(request, response);
    }

}

RapChieuPhim/src/java/controller/CTPhimServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package controller;

import dal.LichChieuDAO;
import dal.NgayChieuDAO;
import dal.PhimDAO;
import dal.RapChieuDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import model.LichChieu;
import model.NgayChieu;
import model.Phim;
import model.RapChieu;

/**
 *
 * @author Admin
 */
public class CTPhimServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        String ID_raw = request.getParameter("ID");
        int ID;
        try {
            ID = Integer.parseInt(ID_raw);
            PhimDAO dao = new PhimDAO();
            Phim p = dao.getPhimByID(ID);
            request.setAttribute("ctphim", p);
            RapChieuDAO dao2 = new RapChieuDAO();
            List<RapChieu> list = dao2.getAllRapChieuByPhimId(ID);
            request.setAttribute("rap", list);
            request.getRequestDispatcher("ctphim.jsp").forward(request, response);
        } catch (NumberFormatException e){
            System.out.println(e);
        }
    } 

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        String PhimId_raw = request.getParameter("phimId");
        String RapId_raw = request.getParameter("rapId");
        int PhimId, RapId;
        try {
            PhimId = Integer.parseInt(PhimId_raw);
            RapId = Integer.parseInt(RapId_raw);
            LichChieuDAO dao3 = new LichChieuDAO();
            List<LichChieu> list = dao3.getAllLichChieuByPhimIdAndRapId(PhimId, RapId);
            request.setAttribute("lich", list);
            NgayChieuDAO dao4 = new NgayChieuDAO();
            List<NgayChieu> list4 = dao4.getAllNgayChieuByPhimIdAndRapId(PhimId, RapId);
            request.setAttribute("ngay", list4);
            PhimDAO dao5 = new PhimDAO();
            Phim p = dao5.getPhimByID(PhimId);
            request.setAttribute("ctphim", p);
            RapChieuDAO dao6 = new RapChieuDAO();
            List<RapChieu> list6 = dao6.getAllRapChieuByPhimId(PhimId);
            request.setAttribute("rap", list6);
            RapChieu rc = dao6.getRapChieuByID(RapId);
            request.setAttribute("rc", rc.getTenRap());
            request.getRequestDispatcher("ctphim.jsp").forward(request, response);
        } catch (NumberFormatException e){
            System.out.println(e);
        }
    }

}

RapChieuPhim/web/admin_lichchieu.jsp
<%-- 
    Document   : admin_lichchieu
    Created on : May 22, 2023, 11:18:34 PM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Quản lí</title>
        <style>
            .adminquanli {
                width: 65vw;
                overflow: auto;
                margin: auto;
                margin-left: 25vw;
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background-color: rgb(211, 248, 216);
                box-shadow: 0 1px 2px 0 rgb(60 64 67 / 10%), 0 2px 6px 2px rgb(60 64 67 / 15%);
                text-align: center;
                padding-bottom: 50px;
            }
            
            .adminquanli h2{
                margin: 20px;
            }

            .adminquanli .button {
                width: 300px;
                margin: auto;
                margin-top: 50px;
            }
            
            .adminquanli .button a {
                border: 1px solid #00cccc;
                display: block;
                height: 50px;
                font-size: 20px;
                line-height: 50px;
                border-radius: 10px;
                text-decoration: none;
                background-color: #00cccc;
                color: white;
                
            }
            
            .adminquanli .button a:hover {
                background-color: #009999;
            }
            
        </style>
    </head>
    <body>
        <br/>
        <%@include file="header.jsp" %>
        <br/>
        <%@include file="menu.jsp" %>
        <br/>
        <%@include file="admin_menu.jsp" %>
        <div class="adminquanli">
            <br/>
            <h2>QUẢN LÝ LỊCH CHIẾU</h2>
        <c:forEach items="${requestScope.dsrap}" var="rap">
            <div class="button"><a href="adminquanlyphongchieu?ID=${rap.ID}"><h3>${rap.tenRap}</h3></a></div>
        </c:forEach>
            
        </div>
        
        
    </body>
</html>

RapChieuPhim/web/ctphim.jsp
<%-- 
    Document   : ctphim
    Created on : Apr 30, 2023, 11:03:10 AM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <c:set value="${requestScope.ctphim}" var="c"/>
        <title>${c.tenPhim}</title>
        <style>
            .ctphim {
                width: 80vw;
                margin: auto;
                overflow: auto;
                background: rgb(231, 248, 233);
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                box-shadow: 0 1px 2px 0 rgb(60 64 67 / 10%), 0 2px 6px 2px rgb(60 64 67 / 15%); 
            }

            .ctphim .tenphim {
                margin-left: 5%;
                font-size: 1.5vw;
            }

            .ctphim .ndphim{
            }

            .ctphim .ndphim .hinhanh {
                position: relative;
                width: 30%;
                padding-bottom: 40%;
                margin-top: 5%;
                left: 5%;
                margin-bottom: 5%;
                border: 1px solid black;
                float: left;
            }

            .ctphim .ndphim .hinhanh img {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
            }  

            .ctphim .ndphim .mota {
                box-shadow: 0 1px 2px 0 rgb(60 64 67 / 10%), 0 2px 6px 2px rgb(60 64 67 / 15%); 
                width: 55%;
                padding-bottom: 50%;
                float: right;
                position: relative;
                right: 5%;
                margin-top: 5%;
                margin-bottom: 5%;
            }

            .ctphim .ndphim .mota .mota_con {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                padding: 2%;
                font-size: 1.5vw;
                background:#ffffff;
            }
            
            .ctphim .ndphim .mota .mota_con h3 {
                text-align: center;
            }
            
            .ctphim .ndphim .mota .mota_con label {
                font-weight: bold;
            }

            .clr {
                clear: both;
            }

            .ctphim .ndphim .ctndphim {
                width: 90%;
                margin: auto;
                margin-bottom: 5%;
                overflow: auto;
                font-size: 1.5vw;
            }
            
            .ctphim .ndphim .ctndphim h4 {
                color: #006080;
            }
            
            .clr {
                clear: both;
            }
            
            .ctphim .ndphim .rap .nut{
                width: 20%;
                line-height: 4vw;
                text-align: center;
                font-weight: bold;
                margin: 2vw;
                float: left;
                
                
            }
            
            .ctphim .ndphim .rap .nut a {
                display: block;
                line-height: 4vw;
                border: 0.25vw solid rgb(0, 74, 0);
                color: rgb(0, 74, 0);
                border-radius: 2vw;
            }
            
            .ctphim .ndphim .rap .nut a:hover {
                background: rgb(0, 74, 0);
                color: white;
            }
            
            .ctphim .ndphim .ctndphim .lich {
                width: 80%;
                min-height: 10vw;
                background: white;
                margin: auto;
                display: block;
                overflow: auto;
                padding: 1vw;
            }
            
            .ctphim .ndphim .rap .lich .ngay {
                border-bottom: 0.25vw solid rgb(2, 46, 13);
                width: 10vw;
                text-align: center;
                padding: 0.3vw;
            }
            
            .ctphim .ndphim .rap .lich a {
                text-decoration: none;
                color: black;
                display: block;
            }
            
            .ctphim .ndphim .rap .lich .lichc {
                border: 0.25vw solid rgb(2, 46, 13);
                border-radius: 0.5vw;
                width: 15vw;
                text-align: center;
                padding: 0.3vw;
                margin: 0.5vw;
                float: left;
            }
        </style>
    </head>
    <body>
        <br/>
        <%@include file="header.jsp" %>
        <br/>
        <%@include file="menu.jsp" %>
        <div class="ctphim">
            <div class="tenphim">
                <h2>${c.tenPhim}</h2>
            </div>
            <hr/>
            
            <div class="ndphim">
                <div class="hinhanh"><img src="${pageContext.request.contextPath}/img/img_phim/${c.hinhAnh}" alt="${c.tenPhim}"></div>
                <div class="mota">
                    <div class="mota_con">
                        <h3> ${c.tenPhim}</h3>
                        <c:if test="${c.dichTenPhim != null}">
                            <p>
                                <label>Tên phim: </label>
                                <span> ${c.dichTenPhim} </span>
                            </p>
                        </c:if>
                            <p>
                                <label>Thể loại: </label>
                                <span> ${c.theLoai} </span>
                            </p>
                        <c:if test="${c.nsx != null}">
                            <p>
                                <label>Nhà sản xuất: </label>
                                <span> ${c.nsx} </span>
                            </p>
                        </c:if>
                            
                        <c:if test="${c.daoDien != null}">
                            <p>
                                <label>Đạo diễn: </label>
                                <span> ${c.daoDien} </span>
                            </p>
                        </c:if>
                        
                        <c:if test="${c.dienVien != null}">
                            <p>
                                <label>Diễn viên: </label>
                                <span> ${c.dienVien} </span>
                            </p>
                        </c:if>
                            
                        <c:if test="${c.dienVien != null}">
                            <p>
                                <label>Quốc gia: </label>
                                <span> ${c.quocGia} </span>
                            </p>
                        </c:if>
                            
                        <c:if test="${c.ngayKhoiChieu != null}">
                            <p>
                                <label>Ngày khởi chiếu: </label>
                                <span> ${c.ngayKhoiChieu} </span>
                            </p>
                        </c:if>
                    </div>
                </div>
                <div class="clr"></div>
                <div class="ctndphim">
                    <h3>Nội dung phim:</h3>
                    <hr/>
                    <p>${c.NDPhim}</p>
                </div>
                
                
                <div class="ctndphim rap">
                    <h3>Lịch chiếu: </h3>
                    <hr/>
                    <form name="myForm2" action="" method="post">
                        <input type="hidden" name="phimId" value="${c.ID}"/>
                        <c:forEach items="${requestScope.rap}" var="rap">
                            <div class="nut">
                                <a type="submit" onclick="checkRap(${rap.ID})">${rap.tenRap}</a>
                            </div>
                        </c:forEach>
                    </form>
                        
                    <script type="text/javascript">
                        function checkRap(RapId){
                            document.myForm2.action = "ctphim?rapId="+RapId;
                            document.myForm2.submit();

                        }
                    </script>
                        
                    <div class="clr"></div>
                        
                    <div class="lich">
                        <c:set value="${requestScope.rc}" var="rc"/>
                        <h3>${rc}</h3>
                        <c:forEach items="${requestScope.ngay}" var="ngay">
                            <p class="ngay">${ngay.ngayChieu}<p>
                            <c:forEach items="${requestScope.lich}" var="lich">
                                <c:if test="${lich.ngayId == ngay.ID}">
                                    <a href="ghe?LichChieuId=${lich.ID}">
                                        <p class="lichc">
                                            <span>${lich.batDau}</span>
                                            <span> - </span>
                                            <span>${lich.ketThuc}</span>
                                        </p>
                                    </a>
                                </c:if>

                            </c:forEach>
                        </c:forEach> 
                    </div>
                    
                </div>
                
            </div>
        </div>
        <%@include file="footer.jsp" %>
    </body>
</html>